project:
  type: website
  output-dir: docs

website:
  title: "Utah Housing Affordability Analysis - STAT 386"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - technical_report.qmd
      - documentation.qmd
      - tutorial.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



